export default function DashboardHeader() {
  return (
    <section
      style={{
        marginBottom: "40px",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <div>
          <h1
            style={{
              margin: 0,
              fontSize: "42px",
              color: "#1E3A8A",
            }}
          >
            📈 AI Opportunity Center
          </h1>

          <p
            style={{
              marginTop: "10px",
              color: "#64748B",
              fontSize: "18px",
            }}
          >
            Discover the strongest investment opportunities generated by MarketPilot AI.
          </p>
        </div>

        <div
          style={{
            background: "#2563EB",
            color: "white",
            padding: "14px 20px",
            borderRadius: "12px",
            fontWeight: "bold",
          }}
        >
          Live Market
        </div>
      </div>
    </section>
  );
}